### ISSUE TITLE
Reconsider nose dependency.

### ISSUE THREAD

**Issue by wdoekes** [VoIPGRID/cacofonisk#1]
As far as I know, there is 0 need to require nose. As I'm allergic to useless dependencies, I'd like to reconsider using the python default tester in favor of nose.

Are there any selling points in this case to using nose over the regular test runner?

**Comment by JorisE** [comment]
To my knowledge, the integatrion in setup.py, makes it very easy to set up coverage and output coverage stats to a xml, which can be used on a CI server (which we don't use right now, but that's another issue :) https://github.com/VoIPGRID/cacofonisk/issues/3)

**Comment by HansAdema** [comment]
`nose` has been removed and coverage is now being used natively with vanilla unittest.
