### ISSUE TITLE
Set up CI for cacofonisk.

### ISSUE THREAD

**Issue by JorisE** [VoIPGRID/cacofonisk#3]
Cacofonisk is currently not automatically tested. We need to set up some kind of CI. We could use the Spindle Jenkins machine at ci.wearespindle.com, but other solutions might be considered.

**Comment by Luit** [comment]
[Travis-CI](https://travis-ci.org/) is very easy to use and well-integrated with Github, and free for open source software. Worth considering.

**Comment by wdoekes** [comment]
Yes. Setting that up this morning for sipp was easy as 123.

https://github.com/SIPp/sipp/blob/master/.travis.yml
- click on the travis link (from web hooks)
- oauth self
- enable sipp repo
- git push anything
- working tests

For a python app it shouldn't be much harder.

**Comment by HansAdema** [comment]
Fixed with PR #9
